### ISSUE TITLE
undefined function mb_strlen()

### ISSUE THREAD

**Issue by phairplay** [d8ahazard/Phlex#128]
hi i've set this up on nginx and seem to be getting the following in the error logs

```
[19-Aug-2017 05:37:09 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function mb_strlen() in C:\nginx-1.8.0\phlex\util.php:925
Stack trace:
#0 C:\nginx-1.8.0\phlex\api.php(76): tail('C:\\nginx-1.8.0\\...', '50')
#1 C:\nginx-1.8.0\phlex\api.php(26): initialize()
#2 {main}
  thrown in C:\nginx-1.8.0\phlex\util.php on line 925
```

**Comment by d8ahazard** [comment]
FIXED with 1fed3460b93f72107db4145f8d09445457ace3ec.
