### ISSUE TITLE
Can't sign in - new installation

### ISSUE THREAD

**Issue by ledfortr** [d8ahazard/Phlex#173]
Installed on Raspberry Pi using the instructions provided.  I am able to successfully bring up my /Phlex/index.php and it says "welcome to Phlex"  when I try to log in, t just says one moment at the bottom and doesn't do anything.  Here is the Phlex_error.log

```
[25-Oct-2017` 21:04:28 America/New_York] PHP Fatal error:  Uncaught Error: Class 'SimpleXMLElement' not found in /var/www/html/Phlex/util.php:676
Stack trace:
#0 /var/www/html/Phlex/api.php(4557): signIn('bGVkZm9ydHJAZ21...')
#1 /var/www/html/Phlex/api.php(23): checkSignIn()
#2 {main}
  thrown in /var/www/html/Phlex/util.php on line 676
[25-Oct-2017 21:08:54 America/New_York] PHP Fatal error:  Uncaught Error: Class 'SimpleXMLElement' not found in /var/www/html/Phlex/util.php:676
Stack trace:
#0 /var/www/html/Phlex/api.php(4557): signIn('bGVkZm9ydHJAZ21...')
#1 /var/www/html/Phlex/api.php(23): checkSignIn()
#2 {main}
  thrown in /var/www/html/Phlex/util.php on line 676
[25-Oct-2017 21:09:09 America/New_York] PHP Fatal error:  Uncaught Error: Class 'SimpleXMLElement' not found in /var/www/html/Phlex/util.php:676
Stack trace:
#0 /var/www/html/Phlex/api.php(4557): signIn('bGVkZm9ydHJAZ21...')
#1 /var/www/html/Phlex/api.php(23): checkSignIn()
#2 {main}
  thrown in /var/www/html/Phlex/util.php on line 676
[25-Oct-2017 21:13:13 America/New_York] PHP Fatal error:  Uncaught Error: Class 'SimpleXMLElement' not found in /var/www/html/Phlex/util.php:676
Stack trace:
#0 /var/www/html/Phlex/api.php(4557): signIn('bGVkZm9ydHJAZ21...')
#1 /var/www/html/Phlex/api.php(23): checkSignIn()
#2 {main}
  thrown in /var/www/html/Phlex/util.php on line 676
```

I'm a noob to linux, so its probably something dumb I did.  I was able to get everything installed fine, php/apache, everything went fine.

**Comment by ledfortr** [comment]
this is in my raspbian log
2017-10-25 21:11:38.391 [WARN ] [.binding.plex.internal.PlexConnector] - Invalid credentials for Plex account
2017-10-25 21:11:39.080 [ERROR] [ab.binding.plex.internal.PlexBinding] - Cannot resolve Plex Media Server host: http://192.168.1.75

**Comment by abrenoch** [comment]
Looks like you are probably missing the XML extension for PHP. If you installed PHP 7 just issue the command `sudo apt-get install php-xml php7.0-mbstring` to install your missing extension. You may also need to enable it in your php.ini file after it is installed.

Another thing to note - I had signed up for plex using my google account, and that does not seem to work well with phlex. It may need to be a native plex account.

**Comment by d8ahazard** [comment]
What @abrenoch said.  I'm going to close this issue as it's already documented in the readme.

Dave, if you want, feel free to open a feature request for Plex/Google support.  I'll have to monkey with this and figure out what I need to do to allow google auth, and see if that would enable easier account linking...

**Comment by ledfortr** [comment]
I put in the command above and it didn't help
