### ISSUE TITLE
Error on util.php, cant save config

### ISSUE THREAD

**Issue by nettosama** [d8ahazard/Phlex#64]
[22-May-2017 00:56:28 UTC] PHP Fatal error:  Uncaught TypeError: Argument 1 passed to array_filter_recursive() must be of the type array, null given, called in /usr/share/nginx/html/Phlex/api.php on line 373 and defined in /usr/share/nginx/html/Phlex/util.php:70
Stack trace:
#0 /usr/share/nginx/html/Phlex/api.php(373): array_filter_recursive(NULL)
#1 {main}
  thrown in /usr/share/nginx/html/Phlex/util.php on line 70
[22-May-2017 01:13:00 UTC] PHP Fatal error:  Uncaught TypeError: Argument 1 passed to array_filter_recursive() must be of the type array, null given, called in /usr/share/nginx/html/Phlex/api.php on line 373 and defined in /usr/share/nginx/html/Phlex/util.php:70
Stack trace:
#0 /usr/share/nginx/html/Phlex/api.php(373): array_filter_recursive(NULL)
#1 {main}
  thrown in /usr/share/nginx/html/Phlex/util.php on line 70

**Comment by nettosama** [comment]
Never mind, that was an old log, it not an issue anymore.
